[common]
configure = [
  "--enable-gpl", "--enable-version3", "--disable-autodetect", "--enable-liblc3",
  "--enable-libass", "--enable-libdav1d", "--enable-libopus", "--enable-libvpx",
  "--enable-libx264", "--enable-libx265", "--enable-libzimg", "--enable-libbluray",
  "--enable-libdvdnav", "--enable-libxml2", "--enable-libaribcaption", "--enable-lv2",
]
encoders = ["libaom-av1", "liblc3", "libmp3lame", "libopus", "libsvtav1", "libvpx-vp9", "libx264", "libx265"]
decoders = ["libdav1d", "liblc3", "libopenjpeg", "libvpx-vp9"]
filters = ["ass", "libplacebo", "libvmaf", "lv2", "qrencode", "qrdecode", "rubberband", "sofalizer", "zscale"]
protocols = ["https", "rist", "srt"]

[targets.linux-x86_64]
configure = ["--enable-vaapi", "--enable-vulkan", "--enable-opencl", "--enable-libvpl", "--enable-nvenc", "--enable-amf", "--enable-librsvg"]
hwaccels = ["vaapi", "vulkan"]
protocols = ["sftp"]
decoders = ["librsvg"]

[targets.linux-arm64]
configure = ["--enable-vaapi", "--enable-vulkan", "--enable-opencl", "--enable-nvenc", "--enable-librsvg"]
hwaccels = ["vaapi", "vulkan"]
protocols = ["sftp"]
decoders = ["librsvg"]

[targets.windows-x86_64]
configure = ["--enable-mediafoundation", "--enable-d3d11va", "--enable-d3d12va", "--enable-dxva2", "--enable-vulkan", "--enable-opencl", "--enable-libvpl", "--enable-nvenc", "--enable-amf"]
hwaccels = ["d3d11va", "d3d12va", "dxva2", "vulkan"]
protocols = ["sftp"]

[targets.windows-arm64]
configure = ["--enable-mediafoundation", "--enable-d3d11va", "--enable-d3d12va", "--enable-dxva2", "--enable-vulkan", "--enable-opencl"]
hwaccels = ["d3d11va", "d3d12va", "dxva2", "vulkan"]

[targets.macos-arm64]
configure = ["--enable-videotoolbox", "--enable-audiotoolbox", "--enable-avfoundation", "--enable-coreimage", "--enable-metal", "--enable-vulkan-static", "--enable-librsvg"]
hwaccels = ["videotoolbox", "vulkan"]
protocols = ["sftp"]
decoders = ["librsvg"]
